#cloudbuild.yaml
steps:

- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/foobar:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/foobar:latest', 'app' ]
  
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
images:
- 'gcr.io/$PROJECT_ID/foobar:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/foobar:latest'
timeout: 3600s
