#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/foobar:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/foobar:latest', '.' ]
# Run the app and dependencies in the background using docker-compose.
# Warning: this won't be cleaned up, which might be an issue if you run it
# with the local builder.
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
images:
- 'gcr.io/$PROJECT_ID/foobar:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/foobar:latest'
timeout: 3600s
