#cloudbuild.yaml
steps:
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/qloud:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/qloud:$COMMIT_SHA']
