#cloudbuild.yaml
steps:
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  
- name: 'docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/qloud:latest', 'app' ]
  
images:
- 'gcr.io/$PROJECT_ID/qloud:latest'
timeout: 3600s
