version: "2"
services:

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    command: --smallfiles

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

  app:
    build: ./app
    links:
      - mongodb
    ports:
      - "5000:5000"
    volumes: ['./app:/app']
