apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/qloud-app/qloud_2:latest
        name: web
        ports:
        - containerPort: 5000
          name: http-server
        imagePullPolicy: Always
